/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Usuario
 */
public class Adquisiciones extends javax.swing.JPanel {
    
    private Controlador controlador;
    /**
     * Creates new form Adquisicion
     */
    public Adquisiciones() {
        initComponents();
    }

    public Adquisiciones(Controlador controlador) {
        this();
        this.controlador = controlador;
        this.formatearTablas();
        this.cargarCombosIniciales();
        this.cargarTablaPlanes();
        //cargar combo medios de pago
        //cargar tabla planes de pago
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonNueva = new javax.swing.JButton();
        botonConcretar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAutomoviles = new javax.swing.JTable();
        txtDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboTiposCompra = new javax.swing.JComboBox<>();
        comboMarcas = new javax.swing.JComboBox<>();
        comboModelos = new javax.swing.JComboBox<>();
        comboAnios = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboMediosDePago = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboPlanes = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPlanes = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADQUISICIONES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        botonNueva.setText("Nueva");
        botonNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaActionPerformed(evt);
            }
        });

        botonConcretar.setText("Concretar");
        botonConcretar.setEnabled(false);
        botonConcretar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConcretarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.setEnabled(false);

        botonModificar.setText("Modificar");
        botonModificar.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(botonNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(botonConcretar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConcretar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("DNI CLiente:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        botonBuscar.setText("Buscar Cliente");
        botonBuscar.setEnabled(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Plan de pago:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 450, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Medio de pago:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        tablaAutomoviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaAutomoviles);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, 90));

        txtDni.setEnabled(false);
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 109, -1));

        jLabel7.setText("Modelo");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel8.setText("Año");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 30, -1));

        comboTiposCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTiposCompraMouseClicked(evt);
            }
        });
        comboTiposCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposCompraActionPerformed(evt);
            }
        });
        jPanel4.add(comboTiposCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, -1));

        comboMarcas.setEnabled(false);
        comboMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMarcasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboMarcasMouseEntered(evt);
            }
        });
        comboMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarcasActionPerformed(evt);
            }
        });
        jPanel4.add(comboMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        comboModelos.setEnabled(false);
        comboModelos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboModelosItemStateChanged(evt);
            }
        });
        comboModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboModelosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboModelosMousePressed(evt);
            }
        });
        comboModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModelosActionPerformed(evt);
            }
        });
        jPanel4.add(comboModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 90, -1));

        comboAnios.setEnabled(false);
        comboAnios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAniosItemStateChanged(evt);
            }
        });
        comboAnios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAniosMouseClicked(evt);
            }
        });
        comboAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAniosActionPerformed(evt);
            }
        });
        jPanel4.add(comboAnios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 80, -1));

        jLabel9.setText("Marca");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        comboMediosDePago.setEnabled(false);
        comboMediosDePago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMediosDePagoMouseClicked(evt);
            }
        });
        comboMediosDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMediosDePagoActionPerformed(evt);
            }
        });
        jPanel4.add(comboMediosDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Cliente");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        comboPlanes.setEnabled(false);
        jPanel4.add(comboPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 90, -1));

        tablaPlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaPlanes);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 410, 100));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tipo de compra:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Automovil");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTiposCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposCompraActionPerformed
    
    }//GEN-LAST:event_comboTiposCompraActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
    Cliente cli = this.verificarDniCliente();
        
        
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void comboMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcasActionPerformed
      
    }//GEN-LAST:event_comboMarcasActionPerformed

    private void comboModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModelosActionPerformed
     
    }//GEN-LAST:event_comboModelosActionPerformed

    private void comboAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAniosActionPerformed
       
    }//GEN-LAST:event_comboAniosActionPerformed

    private void comboMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMarcasMouseClicked
        try{
        String nombreMarca = (String) comboMarcas.getSelectedItem();
      Marca marca = this.controlador.buscarMarca(nombreMarca);
      
      comboModelos.removeAllItems();
           List<Automovil>autos = this.controlador.ListarAutomoviles(marca);
          this.actualizarTablaAutomoviles(autos);
            comboModelos.setEnabled(true);
             this.cargarComboModelos(marca);
     
        }catch (Exception ex){
            
        }        
        
       
            
            
  
    }//GEN-LAST:event_comboMarcasMouseClicked

    private void comboModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboModelosMouseClicked
     try{
         String nombreModelo = (String) comboModelos.getSelectedItem();
     
      Modelo modelo = this.controlador.buscarModelo(nombreModelo);
      
      List<Automovil>autos = this.controlador.ListarAutomoviles(modelo);
    // JOptionPane.showMessageDialog(this, "Buscando autos de ese modelo...", "Aviso", INFORMATION_MESSAGE);
      this.actualizarTablaAutomoviles(autos);
            comboAnios.removeAllItems();
            comboAnios.setEnabled(true);      
            this.cargarComboAnios(modelo);
     }catch (Exception ex){
            
        }    
    }//GEN-LAST:event_comboModelosMouseClicked

    private void comboModelosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboModelosItemStateChanged
          
                     
    }//GEN-LAST:event_comboModelosItemStateChanged

    private void comboMarcasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMarcasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcasMouseEntered

    private void comboAniosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAniosItemStateChanged
      
    }//GEN-LAST:event_comboAniosItemStateChanged

    private void comboAniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAniosMouseClicked
        try{
        String anio = (String) comboAnios.getSelectedItem();
        String nombreModelo = (String) comboModelos.getSelectedItem();
        Modelo modelo = this.controlador.buscarModelo(nombreModelo);
        
        List<Automovil>autos = new ArrayList();
        autos.add(this.controlador.buscarAutomovil(modelo, anio));
         //  JOptionPane.showMessageDialog(this, "Cantidad de modelo+año es = " +autos.size(), "Aviso", INFORMATION_MESSAGE);
        this.actualizarTablaAutomoviles(autos);
           }catch (Exception ex){
            
        } 
    }//GEN-LAST:event_comboAniosMouseClicked

    private void comboModelosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboModelosMousePressed
      
    }//GEN-LAST:event_comboModelosMousePressed

    private void comboTiposCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTiposCompraMouseClicked
          String nombreTipo = (String) comboTiposCompra.getSelectedItem();
      TipoCompra tipo = this.controlador.buscarTipoCompra(nombreTipo);
      if (tipo.getNombre() == "Plan de pago" ){
          comboPlanes.setEnabled(true);
          comboPlanes.removeAllItems();
          this.cargarComboPlanes();
      }else{
          comboPlanes.setEnabled(false);
      }
      comboMediosDePago.removeAllItems();
      this.cargarComboMediosDePago();
      comboMediosDePago.setEnabled(true);
    }//GEN-LAST:event_comboTiposCompraMouseClicked

    private void botonConcretarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConcretarActionPerformed
        int ban=0;
        String anio = (String) comboAnios.getSelectedItem();
        
        String nombreModelo = (String) comboModelos.getSelectedItem();
        Modelo modelo = controlador.buscarModelo(nombreModelo);
        
        String nombreTipo = (String) comboTiposCompra.getSelectedItem();
        TipoCompra tipo = controlador.buscarTipoCompra(nombreTipo);
        
        String nombreMedio = (String) comboMediosDePago.getSelectedItem();
        MedioPago medio = this.controlador.buscarMedioPago(nombreMedio);
        
        String nombrePlan = (String) comboPlanes.getSelectedItem();
        PlanDePago plan = this.controlador.buscarPlanDePago(nombrePlan);
        
        Cliente cli = this.verificarDniCliente();
        
        Automovil auto = this.controlador.buscarAutomovil(modelo, anio);
       
        if (cli == null || auto == null ){
            ban=1;
            JOptionPane.showMessageDialog(this, "Debe ingresar un DNI valido y seleccionar el modelo y año de auto a comprar ", "Error", ERROR_MESSAGE);
        }
        
        if (auto.getStock() == 0){
            ban=1;
            JOptionPane.showMessageDialog(this, "No hay stock del vehiculo que desea comprar", "Error", ERROR_MESSAGE);
        }
        
        
        
        if (ban==1){
            JOptionPane.showMessageDialog(this, "No se pudo concretar la compra", "Error", ERROR_MESSAGE);
        }else{
            Calendar h = Calendar.getInstance();
            Date fecha = h.getTime();
              //JOptionPane.showMessageDialog(this, "Stock antes de la compra:  " +auto.getStock() , "Aviso", INFORMATION_MESSAGE);
            int stock = auto.getStock() - 1;
            auto.setStock(stock);
            this.controlador.actualizarAutomovil(auto);
       //    JOptionPane.showMessageDialog(this, "Stock despues de la compra:  " +auto.getStock() , "Aviso", INFORMATION_MESSAGE);
            Adquisicion adqui = new Adquisicion(fecha, cli, auto, medio, plan, tipo);
                    //(Date fecha, Cliente cliente, Automovil auto, MedioPago medioPago, PlanDePago planDePago, TipoCompra tipoCompra, List<Cuota> cuotas)
            adqui.setMonto(auto.getCotizacion());
            if (nombreTipo == "Plan de pago"){
                this.controlador.cargarCuotas(adqui, plan);
            }
            this.controlador.persistirAdquisicion(adqui);
            botonConcretar.setEnabled(false);
            botonNueva.setEnabled(true);
             JOptionPane.showMessageDialog(this, "Adquisicion concretada exitosamente " , "Aviso", INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_botonConcretarActionPerformed

    private void comboMediosDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMediosDePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMediosDePagoActionPerformed

    private void comboMediosDePagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMediosDePagoMouseClicked
        botonConcretar.setEnabled(true);
    }//GEN-LAST:event_comboMediosDePagoMouseClicked

    private void botonNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaActionPerformed
       botonBuscar.setEnabled(true);
       txtDni.setEnabled(true);
       comboMarcas.setEnabled(true);
       botonNueva.setEnabled(false);
    }//GEN-LAST:event_botonNuevaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonConcretar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonNueva;
    private javax.swing.JComboBox<String> comboAnios;
    private javax.swing.JComboBox<String> comboMarcas;
    private javax.swing.JComboBox<String> comboMediosDePago;
    private javax.swing.JComboBox<String> comboModelos;
    private javax.swing.JComboBox<String> comboPlanes;
    private javax.swing.JComboBox<String> comboTiposCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaAutomoviles;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaPlanes;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables

    public void formatearTablas(){
        //formateando tabla cliente
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");//0
        modelo.addColumn("DNI");//1
        modelo.addColumn("Nombre");//2
        modelo.addColumn("Apellido");//3
        modelo.addColumn("Telefono");//4
        modelo.addColumn("Direccion");//5
        this.tablaCliente.setModel(modelo);
        
        //formateando tabla automoviles
        
        DefaultTableModel modelo2 = new DefaultTableModel();
        modelo2.addColumn("Marca");//0
        modelo2.addColumn("Modelo");//1
        modelo2.addColumn("Año");//2
        modelo2.addColumn("Cotizacion");//3
       
        this.tablaAutomoviles.setModel(modelo2);
        
        
        //formateando  tablaPlanes
        
        DefaultTableModel modelo3 = new DefaultTableModel();
        modelo2.addColumn("Id");//0
        modelo2.addColumn("Nombre");//1
        modelo2.addColumn("Cant Cuotas");//2
        modelo2.addColumn("% Interes");//3
       
        this.tablaPlanes.setModel(modelo3);
    }
    
    public void cargarCombosIniciales (){
        List <Marca> listaMarcas = controlador.ListarMarcas();
        
        for(int i = 0; i < listaMarcas.size() ; i++ ){
             comboMarcas.addItem(listaMarcas.get(i).getNombre());
        }
        
        
        List <TipoCompra> listaTiposCompra = controlador.ListarTiposCompra();
        for(int i = 0; i < listaTiposCompra.size() ; i++ ){
             comboTiposCompra.addItem(listaTiposCompra.get(i).getNombre());
        }     
        
        List <MedioPago> listaMediosPago = controlador.ListarMediosPago();
        for(int i = 0; i < listaMediosPago.size() ; i++ ){
             comboMediosDePago.addItem(listaMediosPago.get(i).getNombre());
        } 
       
           
                
    }
    
    public Cliente verificarDniCliente(){
        Cliente clienteTemporal = null;
        char []caracteres = txtDni.getText().toCharArray();
        int ban=0;
        for(int i=0; i< caracteres.length; i++){
            if( Character.isDigit(caracteres[i]) == false){
                ban=1;
                JOptionPane.showMessageDialog(this, "Solo debe ingresar numeros en el campo DNI", "Error", ERROR_MESSAGE);
            }
        }
        
        if(txtDni.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Debe ingresar el DNI antes de presionar el boton Buscar", "Error", ERROR_MESSAGE);
                ban=1;
        }
        if (ban ==0 ){
            int dni = Integer.parseInt(txtDni.getText());
             clienteTemporal = controlador.buscarCliente(dni);
            if (clienteTemporal == null){
                
                JOptionPane.showMessageDialog(this, "El DNI ingresado no corresponde con ningun cliente registrado", "Error", ERROR_MESSAGE);
                txtDni.setText("");
            }else{
            this.cargarTablaCliente(clienteTemporal);
            
            }
        }
        return clienteTemporal;
    }
    
    public void cargarTablaCliente (Cliente cli){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");//0
        modelo.addColumn("DNI");//1
        modelo.addColumn("Nombre");//2
        modelo.addColumn("Apellido");//3
        modelo.addColumn("Telefono");//4
        modelo.addColumn("Direccion");//5
        modelo.setNumRows(1);
                 int i=0;
            modelo.setValueAt(cli.getId(), i, 0);
            modelo.setValueAt(cli.getDni(), i, 1);
            modelo.setValueAt(cli.getNombre(), i, 2);
            modelo.setValueAt(cli.getApellido(), i, 3);
            modelo.setValueAt(cli.getTelefono(), i, 4);
            modelo.setValueAt(cli.getDireccion(), i, 5);
          
        
        this.tablaCliente.setModel(modelo);
    }
    
    public void actualizarTablaAutomoviles (List<Automovil> autos){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Marca");//0
        modelo.addColumn("Modelo");//1
        modelo.addColumn("Año");//2
        modelo.addColumn("Cotizacion");//3
        modelo.addColumn("Stock");

        
        if (!autos.isEmpty()){
             modelo.setRowCount(autos.size());
        
            for(int i = 0; i < autos.size(); i++){
                modelo.setValueAt(autos.get(i).getId(), i, 0);
                modelo.setValueAt(autos.get(i).getModelo().getMarca().getNombre(), i, 1);
                modelo.setValueAt(autos.get(i).getModelo().getNombre(), i, 2);
                modelo.setValueAt(autos.get(i).getYear(), i, 3);
                modelo.setValueAt(autos.get(i).getCotizacion(), i, 4);
                modelo.setValueAt(autos.get(i).getStock(), i, 5);

            }
        
        }
     
       
        this.tablaAutomoviles.setModel(modelo);
    }
    
    
    public void cargarComboModelos (Marca marca){
        
        List <Modelo> listaModelos = controlador.ListarModelos(marca);
        for(int i = 0; i < listaModelos.size() ; i++ ){
             comboModelos.addItem(listaModelos.get(i).getNombre());
         }
    }
    
    public void cargarComboAnios (Modelo modelo){
        List <Automovil> listaAutos = controlador.ListarAutomoviles(modelo);
        for(int i = 0; i < listaAutos.size() ; i++ ){
             comboAnios.addItem(listaAutos.get(i).getYear());
         }
    }
    
    
    public void cargarComboPlanes(){
         List <PlanDePago> listaPlanes = controlador.ListarPlanesDePago();
        for(int i = 0; i < listaPlanes.size() ; i++ ){
             comboPlanes.addItem(listaPlanes.get(i).getNombre());
         }
    }
    
    
    public void cargarTablaPlanes(){
            List<PlanDePago> planes = controlador.ListarPlanesDePago();
            
            DefaultTableModel modelo = new DefaultTableModel();
             modelo.addColumn("Id");//0
             modelo.addColumn("Nombre");//1
             modelo.addColumn("Cant Cuotas");//2
             modelo.addColumn("% Interes");//3
    
         if (!planes.isEmpty()){
             modelo.setRowCount(planes.size());
        
            for(int i = 0; i < planes.size(); i++){
                modelo.setValueAt(planes.get(i).getId(), i, 0);
                modelo.setValueAt(planes.get(i).getNombre(), i, 1);
                modelo.setValueAt(planes.get(i).getCantidadCuotas(), i, 2);
                modelo.setValueAt(planes.get(i).getInteres(), i, 3);
               
            }
            
        }
         this.tablaPlanes.setModel(modelo);
    }
    
    public void cargarComboMediosDePago (){
          List <MedioPago> listaMedios = controlador.ListarMediosPago();
        for(int i = 0; i < listaMedios.size() ; i++ ){
             comboMediosDePago.addItem(listaMedios.get(i).getNombre());
         }
    }
    
}
