/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import modelo.*;
/**
 *
 * @author Usuario
 */
public class AtenderVtv extends javax.swing.JPanel {
private Controlador controlador;
    /**
     * Creates new form AtenderService
     */
    public AtenderVtv() {
        initComponents();
    }

    public AtenderVtv(Controlador controlador) {
        this();
        this.controlador = controlador;
        this.cargarTablaVtv();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        botonModificar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVtv = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botonAtender = new javax.swing.JButton();
        comboEstadoVtv = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtActual = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Atender Vtv");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        botonModificar.setText("Modificar");
        botonModificar.setEnabled(false);

        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel6, java.awt.BorderLayout.PAGE_END);

        tablaVtv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVtv);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("VTVs a realizar en el dia:");

        botonAtender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAtender.setText("AtenderSiguiente");
        botonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtenderActionPerformed(evt);
            }
        });

        comboEstadoVtv.setEnabled(false);
        comboEstadoVtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoVtvActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Motivo por el que desaprobó");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("N° de Vtv Actual:");

        txtActual.setEnabled(false);

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        txtMotivo.setEnabled(false);
        txtMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotivoKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtMotivo);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel2))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(botonAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel3))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(comboEstadoVtv, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEstadoVtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        add(jPanel7, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtenderActionPerformed
       
        EstadoVTV est = this.controlador.buscarEstadoVtv(Long.parseLong("3"));
        List<Vtv> vtvs = this.controlador.ListarVtvsDelDia();
        botonAtender.setEnabled(false);
        int ban=0;
        for (int i=0; i<vtvs.size(); i++){
          Vtv v = vtvs.get(i);
            if (v.getEstadoVTV() == est){
                txtActual.setText(v.getId().toString());
                ban=1;
                break;
            }
        }
        if (ban==0){
            JOptionPane.showMessageDialog(this, "Ya no quedan turnos pendientes en este dia ", "Aviso", INFORMATION_MESSAGE);
        }else{
             comboEstadoVtv.setEnabled(true);
            comboEstadoVtv.addItem("Aprobado");
            comboEstadoVtv.addItem("Desaprobado");
        }
    }//GEN-LAST:event_botonAtenderActionPerformed

    private void comboEstadoVtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoVtvActionPerformed
        String nombreEstado = (String) comboEstadoVtv.getSelectedItem();
        if(nombreEstado == ""){
            botonGuardar.setEnabled(false);
        }
        if (nombreEstado == "Desaprobado"){
            txtMotivo.setEnabled(true);
            botonGuardar.setEnabled(false);
        }else{
            txtMotivo.setEnabled(false);
            botonGuardar.setEnabled(true);
        }     
        
    }//GEN-LAST:event_comboEstadoVtvActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try{
        String nombreEstado = (String) comboEstadoVtv.getSelectedItem();
        Vtv vtvActual = this.controlador.buscarVtv(Long.parseLong(txtActual.getText()));
        if (nombreEstado == "Desaprobado" && txtMotivo.getText() == ""){
        JOptionPane.showMessageDialog(this, "Debe ingresar el/los motivo/s por el que se desparobó", "Error", ERROR_MESSAGE);
        }else{
            if (nombreEstado == "Desaprobado"){
                vtvActual.setMotivoParaDesaprobar(txtMotivo.getText());
            }
            EstadoVTV ev = this.controlador.buscarEstadoVTV(nombreEstado);
            vtvActual.setEstadoVTV(ev);
            this.controlador.actualizarVtv(vtvActual);
            JOptionPane.showMessageDialog(this, "La vtv se actualizo correctamente ", "Aviso", INFORMATION_MESSAGE);
            this.cargarTablaVtv();
            botonGuardar.setEnabled(false);
            botonAtender.setEnabled(true);
            txtActual.setText("");
            comboEstadoVtv.removeAllItems();
        }
        }catch (Exception ex){}
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void txtMotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotivoKeyTyped
        botonGuardar.setEnabled(true);
    }//GEN-LAST:event_txtMotivoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtender;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JComboBox<String> comboEstadoVtv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVtv;
    private javax.swing.JTextField txtActual;
    private javax.swing.JTextArea txtMotivo;
    // End of variables declaration//GEN-END:variables


    public void cargarTablaVtv (){
        //normalmente se crearia con un Calendar.getInstance asi:
        //Calendar cal = Calendar.getInstance();
        //al ser un caso de prueba seteamos el dia como el primero de julio para que pase la prueba
        
        
        List<Vtv>listaVtv = this.controlador.ListarVtvsDelDia();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");//0
        modelo.addColumn("Hora");//1
        modelo.addColumn("Estado");//2
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        if (!listaVtv.isEmpty()){
             modelo.setRowCount(listaVtv.size());
        
            for(int i = 0; i < listaVtv.size(); i++){
                //cargo el combo de los turnos
                System.out.println("Turnos vtv de hoy: "+ listaVtv.get(i).getId());
                //cargo la tabla de los turnos
                modelo.setValueAt(listaVtv.get(i).getId(), i, 0);
                
                modelo.setValueAt(sdf.format(listaVtv.get(i).getTurno().getFecha()), i, 1);
                modelo.setValueAt(listaVtv.get(i).getTurno().getHora(), i, 2);
                modelo.setValueAt(listaVtv.get(i).getEstadoVTV().getNombre(), i, 3);
                

            }
        
        }else{
            System.out.println("Lista turnos vtv vacia");
        }
     
       
        this.tablaVtv.setModel(modelo);
    }
    
}
