/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Controlador controlador;
    
    
        
    
    public MenuPrincipal() {
        initComponents();
    }
    /*se crea la vista y se carga el controlador que se paso desde el main
    */
    public MenuPrincipal(Controlador ctr) {
        this();
        this.controlador = ctr;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        panelActual = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemGestionarAdquisiciones = new javax.swing.JMenuItem();
        itemListarAdquisiciones = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemProcesarVenta = new javax.swing.JMenuItem();
        itemRegistrarVenta = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemAtenderVtv = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelActual.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Adquisiciones");

        itemGestionarAdquisiciones.setText("Gestionar");
        itemGestionarAdquisiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarAdquisicionesActionPerformed(evt);
            }
        });
        jMenu1.add(itemGestionarAdquisiciones);

        itemListarAdquisiciones.setText("Listar");
        jMenu1.add(itemListarAdquisiciones);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        itemProcesarVenta.setText("Procesar");
        itemProcesarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProcesarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(itemProcesarVenta);

        itemRegistrarVenta.setText("Registrar");
        itemRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(itemRegistrarVenta);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("VTV");

        itemAtenderVtv.setText("AtenderVTV");
        itemAtenderVtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAtenderVtvActionPerformed(evt);
            }
        });
        jMenu9.add(itemAtenderVtv);

        jMenuBar1.add(jMenu9);

        jMenu3.setText("Planes de pago");

        jMenuItem9.setText("Gestionar");
        jMenu3.add(jMenuItem9);

        jMenuItem8.setText("Listar");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Automoviles");

        jMenuItem6.setText("Gestionar");
        jMenu4.add(jMenuItem6);

        jMenuItem10.setText("Listar");
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Clientes");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Empleados");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Medios de Pago");

        jMenuItem11.setText("Gestionar");
        jMenu7.add(jMenuItem11);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Testdrives");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActual, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActual, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestionarAdquisicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarAdquisicionesActionPerformed
        Adquisiciones ad = new Adquisiciones(controlador);
         this.cambiarPanel(ad);
        
        
    }//GEN-LAST:event_itemGestionarAdquisicionesActionPerformed

    private void itemProcesarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProcesarVentaActionPerformed
         ProcesarVenta ad = new ProcesarVenta(controlador);
         this.cambiarPanel(ad);
    }//GEN-LAST:event_itemProcesarVentaActionPerformed

    private void itemRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarVentaActionPerformed
        ConcretarVenta ad = new ConcretarVenta(controlador);
         this.cambiarPanel(ad);
    }//GEN-LAST:event_itemRegistrarVentaActionPerformed

    private void itemAtenderVtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAtenderVtvActionPerformed
        AtenderVtv av = new AtenderVtv(controlador);
        this.cambiarPanel(av);
    }//GEN-LAST:event_itemAtenderVtvActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAtenderVtv;
    private javax.swing.JMenuItem itemGestionarAdquisiciones;
    private javax.swing.JMenuItem itemListarAdquisiciones;
    private javax.swing.JMenuItem itemProcesarVenta;
    private javax.swing.JMenuItem itemRegistrarVenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel panelActual;
    // End of variables declaration//GEN-END:variables


private void cambiarPanel(JPanel panel) {
        panelActual.removeAll();
        panelActual.add(panel,BorderLayout.CENTER);
        panelActual.revalidate();
        panelActual.paintAll(getGraphics());
    }

}
